# build_match_index.ps1 - generate ..\match-index.js from details\<id>.json
# (specs/003-user-auth-profiles, task T036).
#
# Heuristically scans the ENGLISH detail sections for nationality / language
# signals used by client-side matching (match.js). Absent signals stay absent:
# the matcher treats unknown as neutral, never as "not eligible".
# Windows PowerShell 5.1; output is UTF-8 WITHOUT BOM (browser-safe).

$ErrorActionPreference = 'Stop'
$root       = Split-Path -Parent $MyInvocation.MyCommand.Path
$detailsDir = Join-Path $root 'details'
$outFile    = Join-Path (Split-Path -Parent $root) 'match-index.js'

if (-not (Test-Path $detailsDir)) { Write-Error "details folder not found: $detailsDir" }

# Section headers that talk about who can apply / required languages
$eligHeaderRx = '(?i)eligib|nationalit|who\s+can\s+apply|criteria|open\s+to|requirement'
$langHeaderRx = '(?i)language'

# Country names recognised inside eligibility text (catalogue countries + common ones)
$countries = @(
  'Australia','Austria','Belgium','Canada','China','Denmark','Egypt','Finland','France',
  'Germany','Greece','Hungary','India','Indonesia','Ireland','Italy','Japan','Jordan',
  'Kenya','Kuwait','Lebanon','Malaysia','Mexico','Morocco','Netherlands','New Zealand',
  'Nigeria','Norway','Oman','Pakistan','Palestine','Poland','Portugal','Qatar','Romania',
  'Russia','Saudi Arabia','Singapore','South Africa','South Korea','Spain','Sweden',
  'Switzerland','Syria','Tunisia','Turkey','Ukraine','United Arab Emirates',
  'United Kingdom','United States','Yemen','Algeria','Iraq','Libya','Sudan','Bahrain',
  'Brazil','Argentina','Chile','Colombia','Ethiopia','Ghana'
)
$languages = @(
  'English','French','German','Spanish','Italian','Arabic','Chinese','Mandarin',
  'Japanese','Korean','Russian','Turkish','Dutch','Swedish','Norwegian','Danish',
  'Portuguese','Polish','Czech','Hungarian','Romanian','Indonesian'
)

function Strip-Html([string]$s) {
  if (-not $s) { return '' }
  return ($s -replace '<[^>]+>', ' ') -replace '\s+', ' '
}

$index = [ordered]@{}
$files = Get-ChildItem $detailsDir -Filter *.json
$withSignals = 0

foreach ($f in $files) {
  try {
    $j = Get-Content $f.FullName -Raw -Encoding UTF8 | ConvertFrom-Json
  } catch {
    Write-Warning "Skipping unreadable $($f.Name): $_"
    continue
  }
  if (-not $j.en -or -not $j.en.sections) { continue }

  $natFound  = New-Object System.Collections.Generic.List[string]
  $langFound = New-Object System.Collections.Generic.List[string]

  foreach ($sec in $j.en.sections) {
    $header = [string]$sec.header
    $body   = Strip-Html ([string]$sec.body)
    if (-not $body) { continue }

    if ($header -match $eligHeaderRx) {
      foreach ($c in $countries) {
        if ($body -match ('(?i)\b' + [regex]::Escape($c) + '\b') -and -not $natFound.Contains($c)) {
          $natFound.Add($c)
        }
      }
    }
    if ($header -match $langHeaderRx -or $header -match $eligHeaderRx) {
      foreach ($l in $languages) {
        if ($body -match ('(?i)\b' + [regex]::Escape($l) + '\b') -and -not $langFound.Contains($l)) {
          $langFound.Add($l)
        }
      }
    }
  }

  if ($natFound.Count -eq 0 -and $langFound.Count -eq 0) { continue }
  $withSignals++

  $entry = [ordered]@{}
  if ($natFound.Count -gt 0) {
    # exclude lists are intentionally empty in v1: text-mined exclusions are too
    # unreliable to flag people out (contract: caution only on unambiguous signals)
    $entry['nationality_signals'] = [ordered]@{ include = @($natFound); exclude = @() }
  }
  if ($langFound.Count -gt 0) { $entry['language_signals'] = @($langFound) }
  $index[[string]$j.id] = $entry
}

$json = $index | ConvertTo-Json -Depth 6 -Compress
if ($index.Count -eq 0) { $json = '{}' }
$js = "// GENERATED by ScholarShips_Data/build_match_index.ps1 - do not edit by hand.`n" +
      "// Heuristic nationality/language signals mined from extracted detail text.`n" +
      "window.MATCH_INDEX = $json;`n"

[IO.File]::WriteAllText($outFile, $js, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "match-index.js written: $outFile"
Write-Host ("coverage: {0} of {1} detail files yielded signals ({2} nationality, {3} language)" -f `
  $withSignals, $files.Count, `
  (@($index.Values | Where-Object { $_.Contains('nationality_signals') }).Count), `
  (@($index.Values | Where-Object { $_.Contains('language_signals') }).Count))
