<#
build_catalogue.ps1 - Scholarships Data Integration (feature 001)

GENERATES `scholarships.js` at the repository root. That file is generated;
do NOT edit it by hand. Re-run this script whenever any `*.clean.json` changes:

    powershell -ExecutionPolicy Bypass -File ScholarShips_Data\build_catalogue.ps1

What it does (see specs/001-scholarships-data-integration/contracts/):
  1. Reads every `*.clean.json` file in this script's own directory.
  2. Aggregates all records into one list.
  3. De-duplicates by `id` (falls back to `url` when `id` is missing).
  4. Drops expired opportunities (records whose `days` is a number <= 0).
  5. Scrubs visible "For9a"/Arabic-brand tokens from titles/orgs (US7, FR-027/028).
  6. Writes `window.SCHOLARSHIPS = [...]` to `scholarships.js` at the repo root
     (UTF-8, no BOM).

No Python required - pure PowerShell, native to Windows.
#>

$ErrorActionPreference = 'Stop'

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $here
$outputPath = Join-Path $repoRoot 'scholarships.js'

$files = Get-ChildItem -Path $here -Filter '*.clean.json' | Sort-Object Name
if ($files.Count -eq 0) {
    Write-Error "No *.clean.json files found in $here"
    exit 1
}

# --- US7 / FR-027-028: remove visible "For9a" (English) and the Arabic brand
# word "Forsa" from user-facing text. Arabic glyphs are built from hex code points
# at runtime so this SOURCE file stays pure ASCII (no UTF-8 BOM needed under PS 5.1).
$brandWord   = -join [char[]](0x0641,0x0631,0x0635,0x0629)            # Forsa (the brand word)
$brandPrep   = -join [char[]](0x0639,0x0644,0x0649)                   # "on"  (precedes the brand)
$arArticle   = -join [char[]](0x0627,0x0644)                          # "the" article
$arPrefixes  = -join [char[]](0x0648,0x0641,0x0628,0x0643,0x0644)     # conj/prep prefixes w f b k l
$arPunct     = -join [char[]](0x060C,0x061B)                          # Arabic comma + semicolon
$reBrandPrep = $brandPrep + '\s+' + $brandWord                        # "on Forsa"
$reBrandWord = '[' + $arPrefixes + ']*(?:' + $arArticle + ')?' + $brandWord
$rePunctFix  = '\s+([.,;:!?' + $arPunct + '])'

function Remove-Brand([string]$t) {
    if ([string]::IsNullOrEmpty($t)) { return $t }
    $s = $t
    # English: drop a leading connector + brand first ("on/via For9a"), then any token
    $s = [regex]::Replace($s, '(?i)\b(?:on|via|at|through|from|with)\s+for9a\b', '')
    $s = [regex]::Replace($s, '(?i)for9a', '')
    # Arabic: drop "<prep> <word>" ("on Forsa") first, then the word with any attached prefix/article
    $s = [regex]::Replace($s, $script:reBrandPrep, '')
    $s = [regex]::Replace($s, $script:reBrandWord, '')
    # tidy: strip any inline/block tags left empty, collapse spaces, fix space-before-punct
    $s = [regex]::Replace($s, '(?is)<(strong|em|b|i|span|a)\b[^>]*>\s*</\1>', '')
    $s = [regex]::Replace($s, '(?is)<(p|li|h[1-4]|blockquote)\b[^>]*>\s*</\1>', '')
    $s = [regex]::Replace($s, '[ \t]{2,}', ' ')
    $s = [regex]::Replace($s, $script:rePunctFix, '$1')
    return $s.Trim()
}

$rawCount = 0
$expiredDropped = 0
$brandScrubbed = 0
$seen = New-Object 'System.Collections.Generic.HashSet[string]'
$catalogue = New-Object System.Collections.ArrayList

foreach ($file in $files) {
    $records = Get-Content -LiteralPath $file.FullName -Raw -Encoding UTF8 | ConvertFrom-Json
    if ($null -eq $records) { continue }
    if ($records -isnot [System.Array]) { $records = @($records) }
    foreach ($r in $records) {
        $rawCount++

        # Expired = numeric days <= 0. null/None => rolling => keep.
        $days = $r.days
        if ($null -ne $days -and ($days -is [int] -or $days -is [long] -or $days -is [double]) -and $days -le 0) {
            $expiredDropped++
            continue
        }

        # Identity: prefer id, fall back to url.
        $key = $null
        if ($null -ne $r.id -and "$($r.id)".Trim() -ne '') {
            $key = "id:$($r.id)"
        } else {
            $key = "url:$($r.url)"
        }
        if ($seen.Contains($key)) { continue }
        [void]$seen.Add($key)

        # US7: scrub visible brand from the only user-facing free-text card fields.
        # url/image are never shown as visible words, so they stay untouched (spec note).
        foreach ($prop in @('title', 'org')) {
            if ($null -ne $r.$prop) {
                $orig = [string]$r.$prop
                $clean = Remove-Brand $orig
                if ($clean -ne $orig) { $brandScrubbed++ }
                $r.$prop = $clean
            }
        }

        [void]$catalogue.Add($r)
    }
}

$json = $catalogue | ConvertTo-Json -Depth 10
# ConvertTo-Json emits a bare object (not an array) when there is exactly one item.
if ($catalogue.Count -eq 1) { $json = "[`n$json`n]" }

$banner = @"
// AUTO-GENERATED by ScholarShips_Data/build_catalogue.ps1 - DO NOT EDIT.
// Re-run the script after changing any *.clean.json file.
"@

$content = "$banner`nwindow.SCHOLARSHIPS = $json;`n"

# Write UTF-8 without BOM so the browser parses emoji/flags correctly.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputPath, $content, $utf8NoBom)

Write-Host "Read $($files.Count) *.clean.json files"
Write-Host "Raw records: $rawCount | Unique: $($catalogue.Count) | Expired dropped: $expiredDropped | Final: $($catalogue.Count)"
Write-Host "Brand-scrubbed title/org fields: $brandScrubbed"
Write-Host "Wrote scholarships.js (window.SCHOLARSHIPS, $($catalogue.Count) records)"
