<#
build_catalogue.ps1 — Scholarships Data Integration (feature 001)

GENERATES `scholarships.js` at the repository root. That file is generated;
do NOT edit it by hand. Re-run this script whenever any `*.clean.json` changes:

    powershell -ExecutionPolicy Bypass -File ScholarShips_Data\build_catalogue.ps1

What it does (see specs/001-scholarships-data-integration/contracts/):
  1. Reads every `*.clean.json` file in this script's own directory.
  2. Aggregates all records into one list.
  3. De-duplicates by `id` (falls back to `url` when `id` is missing).
  4. Drops expired opportunities (records whose `days` is a number <= 0).
  5. Writes `window.SCHOLARSHIPS = [...]` to `scholarships.js` at the repo root
     (UTF-8, no BOM).

No Python required — pure PowerShell, native to Windows.
#>

$ErrorActionPreference = 'Stop'

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $here
$outputPath = Join-Path $repoRoot 'scholarships.js'

$files = Get-ChildItem -Path $here -Filter '*.clean.json' | Sort-Object Name
if ($files.Count -eq 0) {
    Write-Error "No *.clean.json files found in $here"
    exit 1
}

$rawCount = 0
$expiredDropped = 0
$seen = New-Object 'System.Collections.Generic.HashSet[string]'
$catalogue = New-Object System.Collections.ArrayList

foreach ($file in $files) {
    $records = Get-Content -LiteralPath $file.FullName -Raw -Encoding UTF8 | ConvertFrom-Json
    if ($null -eq $records) { continue }
    if ($records -isnot [System.Array]) { $records = @($records) }
    foreach ($r in $records) {
        $rawCount++

        # Expired = numeric days <= 0. null/None => rolling => keep.
        $days = $r.days
        if ($null -ne $days -and ($days -is [int] -or $days -is [long] -or $days -is [double]) -and $days -le 0) {
            $expiredDropped++
            continue
        }

        # Identity: prefer id, fall back to url.
        $key = $null
        if ($null -ne $r.id -and "$($r.id)".Trim() -ne '') {
            $key = "id:$($r.id)"
        } else {
            $key = "url:$($r.url)"
        }
        if ($seen.Contains($key)) { continue }
        [void]$seen.Add($key)
        [void]$catalogue.Add($r)
    }
}

$json = $catalogue | ConvertTo-Json -Depth 10
# ConvertTo-Json emits a bare object (not an array) when there is exactly one item.
if ($catalogue.Count -eq 1) { $json = "[`n$json`n]" }

$banner = @"
// AUTO-GENERATED by ScholarShips_Data/build_catalogue.ps1 - DO NOT EDIT.
// Re-run the script after changing any *.clean.json file.
"@

$content = "$banner`nwindow.SCHOLARSHIPS = $json;`n"

# Write UTF-8 without BOM so the browser parses emoji/flags correctly.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputPath, $content, $utf8NoBom)

Write-Host "Read $($files.Count) *.clean.json files"
Write-Host "Raw records: $rawCount | Unique: $($catalogue.Count) | Expired dropped: $expiredDropped | Final: $($catalogue.Count)"
Write-Host "Wrote scholarships.js (window.SCHOLARSHIPS, $($catalogue.Count) records)"
