# build_ranking_index.ps1 — feature 004 (specs/004-ticket-booking)
# Joins the generated catalogue (scholarships.js) to a curated world-ranking
# list (rankings.csv) + manual overrides (rankings-overrides.csv), assigns each
# scholarship a tier + price, and writes:
#   1) ../ranking-index.js   → window.RANKING_INDEX (display only)
#   2) the BEACON RANKING SEED block inside ../supabase-setup.sql (authoritative)
#
# No Python (project constraint). PowerShell 5.1. Outputs are written UTF-8
# without BOM so supabase-setup.sql stays paste-clean and non-ASCII institution
# names survive.
#
# Band → tier → price (edit here to retune):
#   rank <= 200  -> high        $300 (30000)
#   rank <= 500  -> medium      $250 (25000)
#   rank  > 500  -> lowest      $200 (20000)
#   not listed   -> out_of_rank $150 (15000)

$ErrorActionPreference = "Stop"
$root      = Split-Path -Parent $PSScriptRoot          # repo root
$here      = $PSScriptRoot
$catalogue = Join-Path $root "scholarships.js"
$rankCsv   = Join-Path $here "rankings.csv"
$ovrCsv    = Join-Path $here "rankings-overrides.csv"
$outJs     = Join-Path $root "ranking-index.js"
$sqlFile   = Join-Path $root "supabase-setup.sql"

$STOP = @('university','universities','of','the','college','institute','school','for','and','de','la')
function Norm([string]$s){ if($null -eq $s){return ""}; ($s -replace '[^a-zA-Z0-9]','').ToLower() }
function SigTokens([string]$s){
  if($null -eq $s){ return @() }
  ($s.ToLower() -split '[^a-z0-9]+') | Where-Object { $_ -and ($STOP -notcontains $_) }
}
function TierForRank([int]$r){ if($r -le 200){'high'} elseif($r -le 500){'medium'} else {'lowest'} }
$PRICE = @{ 'high'=30000; 'medium'=25000; 'lowest'=20000; 'out_of_rank'=15000 }

# ---- load catalogue (strip the window.SCHOLARSHIPS = ... ; wrapper) ----------
if(-not (Test-Path $catalogue)){ throw "Catalogue not found: $catalogue (run build_catalogue.ps1 first)" }
$raw = Get-Content -Raw -LiteralPath $catalogue
$a = $raw.IndexOf('['); $b = $raw.LastIndexOf(']')
if($a -lt 0 -or $b -lt $a){ throw "Could not locate the JSON array in scholarships.js" }
$items = $raw.Substring($a, $b - $a + 1) | ConvertFrom-Json

# ---- load rankings + overrides ----------------------------------------------
$ranks = @()
if(Test-Path $rankCsv){ $ranks = @(Import-Csv -LiteralPath $rankCsv) }
$ovr = @{}
if(Test-Path $ovrCsv){ Import-Csv -LiteralPath $ovrCsv | ForEach-Object { if($_.scholarship_id){ $ovr[[string]$_.scholarship_id] = $_.tier } } }

# precompute ranking rows: significant tokens + numeric rank
$rankRows = foreach($r in $ranks){
  [pscustomobject]@{ inst=$r.institution; tokens=@(SigTokens $r.institution); rank=[int]$r.rank }
}

# ---- match each scholarship -------------------------------------------------
$results = @()
foreach($it in $items){
  $id = [string]$it.id
  $hay = Norm("$($it.org) $($it.title) $($it.country)")
  $tier = $null; $matchInst = $null
  if($ovr.ContainsKey($id)){
    $tier = $ovr[$id]; $matchInst = "(override)"
  } else {
    foreach($rr in $rankRows){
      if($rr.tokens.Count -eq 0){ continue }
      $all = $true
      foreach($t in $rr.tokens){ if($hay -notlike "*$((Norm $t))*"){ $all=$false; break } }
      if($all){ $tier = TierForRank $rr.rank; $matchInst = $rr.inst; break }
    }
  }
  if(-not $tier){ $tier = 'out_of_rank'; $matchInst = ($it.org) }
  $results += [pscustomobject]@{ id=$id; tier=$tier; price=$PRICE[$tier]; institution=$matchInst }
}

# ---- write ranking-index.js (UTF-8, no BOM) ---------------------------------
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// AUTO-GENERATED by ScholarShips_Data/build_ranking_index.ps1 - DO NOT EDIT.")
[void]$sb.AppendLine("// Display-only tiers/prices; the server (scholarship_rankings) is authoritative.")
[void]$sb.AppendLine("window.RANKING_INDEX = {")
for($i=0; $i -lt $results.Count; $i++){
  $r = $results[$i]
  $inst = ($r.institution -replace '\\','\\\\' -replace '"','\"')
  $comma = if($i -lt $results.Count-1){','}else{''}
  [void]$sb.AppendLine("  ""$($r.id)"": { ""tier"": ""$($r.tier)"", ""price"": $($r.price), ""institution"": ""$inst"" }$comma")
}
[void]$sb.AppendLine("};")
[System.IO.File]::WriteAllText($outJs, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))

# ---- replace the SEED block in supabase-setup.sql ---------------------------
$startMark = "-- >>> BEACON RANKING SEED START (generated by ScholarShips_Data/build_ranking_index.ps1) <<<"
$endMark   = "-- >>> BEACON RANKING SEED END <<<"
$seed = New-Object System.Text.StringBuilder
[void]$seed.AppendLine($startMark)
foreach($r in $results){
  $inst = ($r.institution -replace "'","''")
  [void]$seed.AppendLine("insert into public.scholarship_rankings (scholarship_id, institution, tier, amount_cents) values ('$($r.id)', '$inst', '$($r.tier)', $($r.price)) on conflict (scholarship_id) do update set institution = excluded.institution, tier = excluded.tier, amount_cents = excluded.amount_cents, updated_at = now();")
}
[void]$seed.Append($endMark)

$sql = Get-Content -Raw -LiteralPath $sqlFile
$si = $sql.IndexOf($startMark)
$ei = $sql.IndexOf($endMark)
if($si -ge 0 -and $ei -ge $si){
  $before = $sql.Substring(0, $si)
  $after  = $sql.Substring($ei + $endMark.Length)
  $sql = $before + $seed.ToString() + $after
} else {
  $sql = $sql.TrimEnd() + "`r`n`r`n" + $seed.ToString() + "`r`n"
}
[System.IO.File]::WriteAllText($sqlFile, $sql, (New-Object System.Text.UTF8Encoding($false)))

$byTier = $results | Group-Object tier | ForEach-Object { "$($_.Name)=$($_.Count)" }
Write-Host "ranking-index.js + SQL seed written for $($results.Count) scholarships. Tiers: $($byTier -join ', ')"
